server:
  port: ${coisini.defs.server-port}

spring:
  application:
    name: ${coisini.defs.app-name}
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${coisini.eureka.url}
  instance:
    metadata-map:
      username: ${coisini.eureka.username}
      password: ${coisini.eureka.password}

logging:
  path: /var/coisini/log/${coisini.defs.app-name}