server:
  port: ${coisini.defs.server-port}

spring:
  application:
    name: ${coisini.defs.app-name}
  profiles:
    active: dev
  datasource:
    url: ${coisini.datasource.url}
    username: ${coisini.datasource.username}
    password: ${coisini.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: 'SELECT 1'
      maximum-pool-size: 15
  redis:
    database: ${coisini.redis.database}
    host: ${coisini.redis.host}
    port: ${coisini.redis.port}
    password: ${coisini.redis.password}
    timeout: 200ms
    jedis:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 0
        max-wait: -1ms

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.work.bizuser.entity

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${coisini.eureka.url}
    registryFetchIntervalSeconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

logging:
  path: /var/coisini/log/${coisini.defs.app-name}