coisini:
  defs:
    app-name: biz-user
    server-port: 18030
  eureka:
#    url: http://127.0.0.1:18010/eureka/
    url: http://106.13.47.126:18010/eureka/
    username: admin
    password: x5zrqj@RZWD
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


