coisini:
  defs:
    app-name: biz-user
    server-port: 18030
  eureka:
#    url: http://127.0.0.1:18010/eureka/
    url: http://106.13.47.126:18010/eureka/
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  redis:
    database: 15
    host: 106.13.89.134
    port: 6379
    password: x5zrqj@RZWD


