coisini:
  defs:
    app-name: biz-auth
    server-port: 18040
  datasource:
    url: jdbc:mysql://106.13.47.126:3306/biz_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: x5zrqj@RZWD
  eureka:
    #    url: http://127.0.0.1:18010/eureka/
    url: http://106.13.89.134:18010/eureka/
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  redis:
    database: 15
    host: 106.13.89.134
    port: 6379
    password: x5zrqj@RZWD
